// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/13/2026, 9:35:47 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/plugins/**/*.{js,ts,mjs}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/composables/**/*.{js,ts,mjs}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/utils/**/*.{js,ts,mjs}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/de-elite/Desktop/De-elite Files/Jobs/Web3/customer-service-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;